kind: pipeline
type: docker
name: mytube-pipeline

platform:
  os: linux
  arch: amd64

steps:
  # Test stage
  - name: test-backend
    image: python:3.12-slim
    commands:
      - cd backend
      - pip install -r requirements.txt
      - python -m pytest tests/ || true  # Run tests if they exist
    when:
      event:
        - push
        - pull_request

  - name: test-frontend
    image: node:18-alpine
    commands:
      - cd frontend
      - npm ci
      - npm run build
      - npm test || true  # Run tests if they exist
    when:
      event:
        - push
        - pull_request

  # Build stage - Backend Base
  - name: build-backend-base
    image: plugins/docker
    settings:
      registry: localhost:5000
      repo: localhost:5000/mytube-backend-base
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:8}
      dockerfile: backend/Dockerfile.base
      context: backend
    when:
      event:
        - push
        - tag

  - name: build-backend-fastapi
    image: plugins/docker
    settings:
      registry: localhost:5000
      repo: localhost:5000/mytube-backend-fastapi
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:8}
      dockerfile: backend/Dockerfile.fastapi
      context: backend
    depends_on:
      - build-backend-base
    when:
      event:
        - push
        - tag

  - name: build-backend-huey
    image: plugins/docker
    settings:
      registry: localhost:5000
      repo: localhost:5000/mytube-backend-huey
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:8}
      dockerfile: backend/Dockerfile.huey
      context: backend
    depends_on:
      - build-backend-base
    when:
      event:
        - push
        - tag

  - name: build-frontend
    image: plugins/docker
    settings:
      registry: localhost:5000
      repo: localhost:5000/mytube-frontend
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:8}
      dockerfile: frontend/Dockerfile
      context: frontend
    when:
      event:
        - push
        - tag

# Trigger conditions
trigger:
  branch:
    - main
    - master
    - develop
  event:
    - push
    - pull_request
    - tag 