version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mytube
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mytube
      - REDIS_URL=redis://redis:6379/0
      - HOST=0.0.0.0
      - PORT=8000
      - WORKERS=4
      - LOG_LEVEL=info
    ports:
      - "8000:8000"
    volumes:
      - ./downloads:/app/downloads
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  huey:
    build:
      context: .
      dockerfile: Dockerfile.huey
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mytube
      - REDIS_URL=redis://redis:6379/0
      - HUEY_WORKERS=4
      - HUEY_VERBOSE=1
      - HUEY_LOG_LEVEL=INFO
    volumes:
      - ./downloads:/app/downloads
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data: 