apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  POSTGRES_HOST: "192.168.1.50"
  DATABASE_URL: "postgresql://mytube:123456@192.168.1.50:5432/mytube"
  REDIS_URL: "redis://redis:6379/0"
  HOST: "0.0.0.0"
  PORT: "8000"
  WORKERS: "4"
  LOG_LEVEL: "info"
  HUEY_WORKERS: "4"
  HUEY_VERBOSE: "1"
  HUEY_LOG_LEVEL: "INFO" 