apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DATABASE_URL: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)"
  REDIS_URL: "redis://redis:6379/0"
  HOST: "0.0.0.0"
  PORT: "8000"
  WORKERS: "4"
  LOG_LEVEL: "info"
  HUEY_WORKERS: "4"
  HUEY_VERBOSE: "1"
  HUEY_LOG_LEVEL: "INFO" 