apiVersion: v1
kind: Service
metadata:
  name: external-postgres
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - port: {{ .Values.backend.postgres.port }}
      targetPort: {{ .Values.backend.postgres.port }}
      protocol: TCP
      name: postgres
  clusterIP: None # Headless service for externalName/endpoint
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-postgres
  namespace: {{ .Values.global.namespace }}
subsets:
  - addresses:
      - ip: {{ .Values.backend.postgres.host }}
    ports:
      - port: {{ .Values.backend.postgres.port }}
        name: postgres 