apiVersion: v1
kind: Secret
metadata:
  name: mytube-backend-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.backend.postgres.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.backend.postgres.password | b64enc }}
  POSTGRES_DB: {{ .Values.backend.postgres.database | b64enc }} 