apiVersion: v1
kind: Secret
metadata:
  name: mytube-backend-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.backend.postgres.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.backend.postgres.password | b64enc }}
  POSTGRES_DB: {{ .Values.backend.postgres.database | b64enc }}
  MINIO_ENDPOINT: {{ .Values.minio.endpoint | b64enc }}
  MINIO_ACCESS_KEY: {{ .Values.minio.accessKey | b64enc }}
  MINIO_SECRET_KEY: {{ .Values.minio.secretKey | b64enc }} 