apiVersion: apps/v1
kind: Deployment
metadata:
  name: huey
  namespace: mytube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: huey
  template:
    metadata:
      labels:
        app: huey
    spec:
      containers:
      - name: huey
        image: localhost:5000/mytube-backend-huey:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secrets
        volumeMounts:
        - name: downloads
          mountPath: /app/downloads
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads-pvc 