# Minimal Drone CI configuration for homelab
env:
  ## Use root path instead of subpath
  DRONE_SERVER_HOST: "drone.homelab.local"
  
  ## REQUIRED: Set the protocol scheme
  DRONE_SERVER_PROTO: "http"
  
  ## REQUIRED: Shared secret to authenticate runners
  DRONE_RPC_SECRET: "super-duper-secret"
  
  ## GitHub Personal Access Token instead of OAuth
  DRONE_GITHUB_CLIENT_ID: "Ov23lisMAulfXNtc2VPl"
  DRONE_GITHUB_CLIENT_SECRET: ""
  DRONE_GIT_USERNAME: "newcl"
  DRONE_GIT_PASSWORD: ""
  
  ## Create admin user
  DRONE_USER_CREATE: "username:newcl,admin:true"
  
  ## Disable registration since using token auth
  DRONE_OPEN: "false"
  
  ## Enable debug logging
  DRONE_LOGS_DEBUG: "true"
  DRONE_LOGS_TRACE: "true"

# Service configuration - fix port mismatch
service:
  type: ClusterIP
  port: 80  # Match what Drone container is listening on

# Root path ingress for simplicity
ingress:
  enabled: true
  className: "traefik"
  hosts:
    - host: drone.homelab.local
      paths:
        - path: /
          pathType: Prefix

# Disable persistence for now
persistentVolume:
  enabled: false